[package]
name = "RustyRolladen"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs = "6.0.0"
serde_json = "0.9.10"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.8.20"
rppal = "0.22.1"
systemd-journal-logger = "2.0.0"
log = "0.4.26"
rand = "0.9.0"
bme680 = "0.6.0"
